location = /admin {
    return 301 /admin/;
}

location ^~ /admin/ {
    alias /www/wwwroot/pasal/admin/;
    try_files $uri $uri/ /admin/index.html;
}

location ^~ /api/ {
    try_files $uri /index.php?$query_string;

    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /www/wwwroot/pasal/backend-laravel/public/index.php;
    fastcgi_param DOCUMENT_ROOT /www/wwwroot/pasal/backend-laravel/public;
    fastcgi_param SCRIPT_NAME /index.php;
    fastcgi_param REQUEST_URI $request_uri;
    fastcgi_param HTTPS on;
    fastcgi_pass unix:/tmp/php-cgi-84.sock;
}

location ~ \.php$ {
    return 404;
}
